name: pawfect
description: "Pawfect - A pet marketplace and management app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Existing dependencies
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  http: ^1.2.2
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.17
  persistent_bottom_nav_bar_v2: ^5.3.1
  bot_toast: ^4.1.3
  intl: ^0.19.0
  lottie: ^3.3.1
  auto_size_text: ^3.0.0

  firebase_core: ^3.9.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.2
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/pngs/
