// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxMJAWKEk7XtyE17T2QXHn_9ZHzZvR3yw',
    appId: '1:455706531945:web:3729f197cc80d511a5aaf8',
    messagingSenderId: '455706531945',
    projectId: 'pawfect-512fc',
    authDomain: 'pawfect-512fc.firebaseapp.com',
    storageBucket: 'pawfect-512fc.firebasestorage.app',
    measurementId: 'G-N0Y077779P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2JJrPl-9jxphlhI8zqNk8CuZYzZPBcQ',
    appId: '1:455706531945:android:52b9478802314798a5aaf8',
    messagingSenderId: '455706531945',
    projectId: 'pawfect-512fc',
    storageBucket: 'pawfect-512fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZq-7yLJyAD4EFx4ooAjxCiHh6cY-KWh0',
    appId: '1:455706531945:ios:0b52407e87d20fa4a5aaf8',
    messagingSenderId: '455706531945',
    projectId: 'pawfect-512fc',
    storageBucket: 'pawfect-512fc.firebasestorage.app',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZq-7yLJyAD4EFx4ooAjxCiHh6cY-KWh0',
    appId: '1:455706531945:ios:0b52407e87d20fa4a5aaf8',
    messagingSenderId: '455706531945',
    projectId: 'pawfect-512fc',
    storageBucket: 'pawfect-512fc.firebasestorage.app',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxMJAWKEk7XtyE17T2QXHn_9ZHzZvR3yw',
    appId: '1:455706531945:web:376ae43ae8dbfb21a5aaf8',
    messagingSenderId: '455706531945',
    projectId: 'pawfect-512fc',
    authDomain: 'pawfect-512fc.firebaseapp.com',
    storageBucket: 'pawfect-512fc.firebasestorage.app',
    measurementId: 'G-5KTMGWRQLG',
  );
}
